config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :teams do
    member do
      get 'detach'
      get 'makeOwner'
      get 'removeOwner'
    end
  end
  resources :leagues
  devise_for :users, :controllers => {:registrations => "registrations", confirmations: 'confirmations'}
  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :user
  has_many :teams, dependent: :destroy
  accepts_nested_attributes_for :teams, allow_destroy: true, reject_if: proc { |att| att['name'].blank? }
  mount_uploader :image, ImageUploader
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  def index
    @leagues = current_user.leagues
  end

  def show
    authorize @league
    @teams = @league.teams.all
    @teams = @teams.order(:wins).reverse_order
  end

  def new
    @league = League.new
  end

  def edit
    authorize @league
  end

  def create
    @league = League.new(league_params)
    @league.user = current_user

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @league
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @league
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_league
      @league = League.find(params[:id])
    end

    def league_params
      params.require(:league).permit(:name, :location, :image, teams_attributes: Team.attribute_names.map(&:to_sym).push(:_destroy))
    end

end

app/helpers/leagues_helper.rb
module LeaguesHelper
  def showEdit(current_user, league)
    if policy(league).edit?
      button_to "Edit League", edit_league_path, :class => "btn-mid center-block", :method => :get
    end
  end
end

app/views/leagues/_form.html.erb
<section>
<%= simple_form_for(@league) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.file_field :image %>
    <p><br></p>
    <%= f.input :name %>
    <%= f.input :location %>
  </div>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Team Name</th>
        <th>Team Icon</th>
      </tr>
    </thead>
    <tbody class='fields'>
      <%= f.simple_fields_for :teams do |builder| %>
        <%= render 'team', f: builder %>
      <% end %>
    </tbody>
  </table>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-primary' %>
    <%= link_to_add_row('Add Team', f, :teams, class: 'btn btn-primary') %>
  </div>
<% end %>
</section>

app/views/leagues/_team.html.erb
<tr>
  <td>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= link_to 'Delete', '#', class: 'remove_record' %>
  </td>
  <td><%= f.input :name, label: false %></td>
  <td><%= f.file_field :image %></td>
</tr>

app/views/leagues/edit.html.erb
<section class = "put-margin">
<p><br></p>
<h1>Edit your League</h1>

<%= render 'form', league: @league %>

<p><br></p>
<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

</section>

app/views/leagues/index.html.erb
<section class = "put-margin">
<p><br></p>
<p id="notice"><%= notice %></p>

<h1>Leagues You Own</h1>

<section>
  <div>
    <div class="container-fluid d-flex justify-content-center">
      <div class="row">
        <% @leagues.each do |league| %>
          <div class="col-lg-3">
            <div class="panel panel-default">
              <div class="panel-heading clearfix do-wrap"><h4><span class = "valign do-wrap"><%= league.name %> </span><div class = "circle pull-right"><%= image_tag(league.image_url(:thumb).to_s) %> </div></h4></div>
   			        <div class="panel-body">
                  <ul class="list-group">
                    <li class="list-group-item"><strong>Location:</strong> <%= league.location %></li>
                    <li class="list-group-item"><%= link_to "More ", league_path(league) %><%= link_to 'Edit ', edit_league_path(league) %> <%= link_to 'Remove', league, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                  </ul>
                </div>
   		       </div>
          </div>
        <% end %>
      </div>
    </div>
    <br><br>
  </div>
</section>

<%= button_to "Create New League", new_league_path, :class => "btn-mid center-block", :method => :get %>

<%= button_to "Go To Your Teams", teams_path, :class => "btn-mid center-block", :method => :get %>

</section>

<p><br></p>

app/views/leagues/new.html.erb
<section class = "put-margin">
<p><br></p>
<h1>Create a New League</h1>

<%= render 'form', league: @league %>

</section>

app/views/leagues/show.html.erb
<section class = "put-margin">
<br>
<p id="notice"><%= notice %></p>

<p style = 'font-size: 4rem' class = "text-center">
  <strong>Name:</strong>
  <%= @league.name %>
  <span class = "circle"><%= image_tag(@league.image_url(:thumb).to_s) %></span>
</p>

<p style = 'font-size: 3rem' class = "text-center">
  <strong>Location:</strong>
  <%= @league.location %>
</p>
<br>
<section>
  <div class>
    <div class="container-fluid d-flex justify-content-center">
      <div class="row">
        <% @teams.each do |team| %>
          <div class="col-md-3">
            <div class="panel panel-default">
              <div class="panel-heading clearfix do-wrap"><h4><span class = "valign do-wrap"><%= team.name %></span> <div class = "circle pull-right"><%= image_tag(team.image_url(:thumb).to_s) %> </div></h4></div>
   			        <div class="panel-body">
                  <ul class="list-group">
                    <li class="list-group-item">Wins: <%= team.wins %></li>
                    <li class="list-group-item">Losses: <%= team.losses %></li>
                  </ul>
                  <% if policy(@league).more? || current_user.teams.exists?(team.id) %>
                    <%= link_to "More ", team_path(team) %>
                  <% end %>
                </div>
   		       </div>
          </div>
        <% end %>
      </div>
    </div>
    <br><br>
  </div>
</section>

<div class="container">
  <h2 class = "text-center">Current Statistics</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Team</th>
        <th>Wins</th>
        <th>Losses</th>
      </tr>
    </thead>
    <tbody>
      <% @teams.each do |team| %>
        <tr>
          <td><%= team.name %></td>
          <td><%= team.wins %></td>
          <td><%= team.losses %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br><br>

<%= showEdit(current_user, @league) %>
<%= button_to "Back To All Leagues", leagues_path, :class => "btn-mid center-block", :method => :get %>


</section>
<br>